type ordering
  Lesser
  Equal
  Greater

pub fun show(order: ordering) : string {
  match order
    Lesser -> "Lesser"
    Equal -> "Equal"
    Greater -> "Greater"
}

pub fun create() {}

pub fun length() {}

pub fun is_empty() {}

pub fun mem() {}

pub fun add() {}

pub fun remove() {}

pub fun union() {}

pub fun intersect() {}

pub fun equal() {}

pub fun any() {}

pub fun all() {}

pub fun find() {}

pub fun nth() {}

pub fun is_subset() {}

pub fun are_disjoint() {}